- README.md
- resources/views/livewire/datatables/checkbox.blade.php
- resources/views/livewire/datatables/datatable.blade.php
- src/Column.php
- src/Http/Livewire/LivewireDatatable.php
In response to #13 
- Adds ```Column::select()``` to create seleactable rows
- Component exposes ```$selected``` array of selected rows
- Adds ```$beforeTableSlot``` and ```$afterTableSlot``` to allow users to add additional templates that can access component properties.
> Adds Selectable rows

- src/Column.php
I have a data set that I want the user to be able to edit if certain conditions are true. This would be most easily accomplished if I could calculate the conditions before creating the column and only setting it to editable if the conditions are met. So what this PR proposes is the addition of an optional parameter to editable(), defaulted to true, that would not set the attribute if the parameter is false.
> Add optional parameter to editable() to allow for conditional setting

- resources/views/livewire/datatables/editable.blade.php
Raw html output that can cause simple takeover by displaying user-entered data should be the hard path (another modifier), not the easy one.
Example:
Display results from a table containing <script>alert('woof!');</script>
This could of course be solved centrally and for all colums (since it happens on string columns too) by escaping it in 
https://github.com/MedicOneSystems/livewire-datatables/blob/9645df8f6c9140624a0ec36d0621b033bd76e12c/src/Http/Livewire/LivewireDatatable.php#L945-L950
but i am not sure if that'd cause display/other issues on the table.
> Values read from the DB should be escaped default

- src/Http/Livewire/LivewireDatatable.php
There is a bug with parenthesis on sql query with making a query on 2 boolean column with the "false" condition.
Making something like: col 1 = true AND col 2 = false OR col 2 is null
The fix do: col 1 = true AND (col 2 = false OR col 2 is null)
> Fix a bug with Multiple filter on boolean column

- resources/views/livewire/datatables/datatable.blade.php
- resources/views/livewire/datatables/delete.blade.php
- resources/views/livewire/datatables/header-no-hide.blade.php
- resources/views/livewire/datatables/hide-column-multiselect.blade.php
- resources/views/livewire/datatables/tailwind-simple-pagination.blade.php
- resources/views/livewire/datatables/tooltip.blade.php
This PR removes some of the duplicate CSS classes in blade files.
> Remove duplicate classes

- config/livewire-datatables.php
I went source diving and found this option can be used in the config, so I think it would be easier for users to see the default in the config so they know they can easily change it.
When I didn't see it in the config, I thought I would need to add this functionality and then PR the whole functionality, but it's already there. 👍  I just think it's easier for users to see it in the config file.
> Add model_namespace to config

- src/Http/Livewire/LivewireDatatable.php
This change fixes the problem of removing all text filters if you click to remove the first one only.
> fix removing all text filters if the key is 0

- src/Http/Livewire/LivewireDatatable.php
The current code determines whether the DB is Postgres or something else by assuming that the default laravel connection names are used.  This PR changes the lookup to get the driver name from the  PDO object underlying the current DB connection.
> Get the DB driver from the current connection

- src/LivewireDatatablesServiceProvider.php
This would fix https://github.com/MedicOneSystems/livewire-datatables/issues/70 for sqlite.
Very likely needs more testing on other Databases/Configurations.
> Fix distinct aggregate breaking on sqlite

- config/livewire-datatables.php
- resources/views/livewire/datatables/datatable.blade.php
- src/Http/Livewire/LivewireDatatable.php
This is to make per-page menu and per-page default configurable by adding them to the config file and then using those values instead of the hard-coded values.  The config() calls default to the previously hard-coded values, so behavior won't change if the config options are missing (i.e. it won't break anything if someone updates the component and view but retains their previous config file).
> Make per-page menu and per-page default configurable

- composer.json
- resources/views/livewire/datatables/header-inline-hide.blade.php
- resources/views/livewire/datatables/header-no-hide.blade.php
- src/Column.php
- src/Http/Livewire/LivewireDatatable.php
- tests/ColumnTest.php
This PR adds width functionality to the column classes so you can define the width of your table columns
`NumberColumn::name('id')->width('1%'),`
In this example the width of the index column is set to 1% of the width of the table so we will have a nice and narrow ID column
It's my first ever PR so please be gentle 😉
> Added width functionality to columns

- src/Http/Livewire/LivewireDatatable.php
This pull request replaced `env('DB_CONNECTION')` with dynamically getting the current DB Connection Driver name because some app uses a custom connection name instead of the default connection name `postgres`, `mysql`, etc.
> Replaced get DB Connection name with the current DB Driver name.

- src/Http/Livewire/LivewireDatatable.php
- The `env` helper will return null if the config is cached, so it's better to default directly to the `config` helper instead.
- Fixes #104 and adds support for multiple database management systems per model (so you can use multiple database connections without being forced to use only one).
> Fix orderBy quotation errors for SQL server

- src/Http/Livewire/LivewireDatatable.php
- src/LivewireDatatablesServiceProvider.php
If we specify a custom aggregate (max, avg, min, ...) use this aggregate for filtering data in place of 'count' if the Column is not a string column.
Also fix filtering when null values are returned with aggregates (use COALESCE for Expression) and allow to put 0 in max value for number filtering
The patch fixes issues #178 and #92
> Add over-ridden aggregates support in filters

- resources/views/livewire/datatables/datatable.blade.php
Just added an `unless()` in `datatable.blade.php` to hide the header along with the rest of the column. Thanks!
> Bugfix for #243 (Column/header shift when hiding a checkbox column)

- src/Http/Livewire/LivewireDatatable.php
Postgres does not allow you to coalesce a non-string like column to empty string. Tested with int, bigint, boolean as well as varchar and text.
> Fix issue with coalescing non-string like columns to empty string

- src/Http/Livewire/LivewireDatatable.php
Updated usage of '$this->activeSelect' to '$this->activeSelectFilters'.
Select filters now persist properly.
> Fixed typo: Updated variable use

- README.md
- config/livewire-datatables.php
- src/Http/Livewire/LivewireDatatable.php
About styling... I agree with your principles as described in the README, but i do think it's easier if the hardcoded classes in the code could be set by default in the config instead of overriding the methods on every datatables component. This makes it easier to apply your own style and makes the code look a bit cleaner on your project.
Because of that i made the following changes:
* Extracting the default CSS classes applied by the rowClasses() and cellClasses() methods to the config file.
* Added a line in the README to let people know they can set these classes in the config.
* Added comments to the config file to make it look and feel more like an original Laravel config file.
As this is my first pull request to an open-source project ever (better late then never), please let me …
> Extract default CSS classes to config.

- src/Column.php
- src/Http/Livewire/LivewireDatatable.php
This feature is unlikely to be used. But to be honest I'm really looking forward to how to add Laravel's `$loop->increment` into this package. I read the documentation, and I don't see any function related to the incremental feature.
I think it could be nice to have such a feature in this package because it helps me a lot.
The usage is simply by using:
```php
\Mediconesystems\LivewireDatatables\Column::index($this);
```
> Add "Row Index" column type

- src/Http/Livewire/LivewireDatatable.php
without set export name : 
```
class DemoTable extends LivewireDatatable
{
public $exportable = true;
// export file name "DatatableExport.xlsx"
}
```
with set export name : 
```
class DemoTable extends LivewireDatatable
{
public $exportable = true;
public $export_name = 'Export Demo';
// export file name "Export Demo.xlsx"
}
```
or
```
class DemoTable extends LivewireDatatable
{
public $exportable = true;
public $export_name = '';
public function __construct()
{
$this->export_name = 'Export Demo ' . date('YmdHis');
}
// export file name "Export Demo 20211116140000.xlsx"
}
```
> Rename export file

- src/Http/Livewire/LivewireDatatable.php
Gets the ```$model``` from the ```builder()``` method if a ```$model``` is not supplied.
> Get $model from builder() method

- README.md
- resources/views/livewire/datatables/datatable.blade.php
- src/Action.php
- src/Exports/DatatableExport.php
- src/Http/Livewire/LivewireDatatable.php
This is completely opinionated. Suggestions are welcome.
```
public function buildActions()
{
return [
Action::value('edit')->label('Edit Selected')->group('Default Options')->callback(function ($mode, $items) {
$this->editHandler($mode, $items);
}),
Action::value('update')->label('Update Selected')->group('Default Options')->callback(function ($mode, $items) {
$this->editHandler($mode, $items);
}),
Action::groupBy('Export Options', function () {
return [
Action::value('csv')->label('Export CSV')->export('SalesOrders.csv'),
Action::value('html')->label('Export HTML')->export('SalesOrders.html'),
Action::value('xlsx')->label('Export XLSX')->export('SalesOrders.xlsx')->styles($this->exportStyles)->widths($this->exportWidths)
];
}),
];
}
public function editHandler($mode, $items)
{
}
public …
```
> Mass action support

- resources/views/livewire/datatables/datatable.blade.php
Hi !
First of all, great work on this lib, it's really a lifesaver for me.
Today, I tested the summary row feature introduced recently, and I saw a bug : when a column left of a summary is hidden, it's still taken into account when creating the table cells of the summary row.
So I'm offering a quick fix here. Everything seems to work on my end, I'll let you test and get back to me if I need to do any changes.
I got some other PRs coming in the future from the customizations I did on my end that could benefit others
> Takes into account hidden columns when displaying summary row

- src/Http/Livewire/LivewireDatatable.php
The highlight call is currently executed after the export callback, making it impossible to strip out the highlighting markup that is added for search results. Moving the highlighting before the export callbacks resolves this.
> Move highlight call before export callback calls.

- resources/views/livewire/datatables/checkbox.blade.php
This change allows you to use the checkbox column even if you're not using the `CanPinRecords` trait.  
Without this in place, rendering the datatable throws a `Property [$pinnedRecords] not found on component`.
With it, you can use the checkbox for pinned records as normal, or add a button, etc. to one of the slots to do something with the selected records.
Thanks!
> Change to allow use of checkbox without 'CanPinRecords'

- src/Column.php
Mediconesystems\LivewireDatatables\Column::callback(): Argument #2 ($callback) must be of type Closure, string given
In src/Column.php:119 you set the type to "Closure" when it should be Closure|string
Add something like this in your columns() method:
```php
Column::callback(['id', 'title'], 'someLocalMethod');
```
> Column::callback(): Argument #2 ($callback) must be of type Closure, string given

- src/Http/Livewire/LivewireDatatable.php
This doesn't seem to be required for postgres either.  This is related to issue #434
> The backtick on the sort string for sqlserv breaks query.

- composer.json
Since [this commit](https://github.com/MedicOneSystems/livewire-datatables/commit/258ed099beea44fec6b5bd84c6a054a36a914402) PHP8 is required. I think latest package release supporting PHP 7 is [0.9.1](https://github.com/MedicOneSystems/livewire-datatables/releases/tag/v0.9.1)
> php 8 is required

- src/Http/Livewire/LivewireDatatable.php
fix error when using Column::callback with tablePrefix
> fix: tablePrefix problem

- resources/views/livewire/datatables/editable.blade.php
- src/Traits/WithCallbacks.php
This is to fix when there're two editable columns in a row, when you edit one the other will be marked as green even it has not been edited.
> Add column argument to 'fieldEdited' event.

- resources/views/livewire/datatables/delete.blade.php
fix delete template to allow the call to delete function on component to work with uuids containing minus signs
> add single quotes around id in call to delete function

- resources/views/livewire/datatables/hide-column-multiselect.blade.php
- src/Column.php
Added in reference to this issue: https://github.com/MedicOneSystems/livewire-datatables/issues/354
```
Column::name('name')
->hideable(false)
```
> Adds hideable functionality to column select

- src/Http/Livewire/LivewireDatatable.php
Set variable `$useThrough` **AFTER** checking if relation is an instance of HasMany, HasManyThrough or BelongsToMany. Otherwise, it will return an error because no joins property exists for `$this->query->getQuery()`
> Bugfix for relations in resolveColumnName method

- src/LivewireDatatablesServiceProvider.php
Fixes issue #491: Add table prefix to the table variable in the customWithAggregate and hasAggregate EloquentBuilder macros registerd by the service provider.
> fix customWithAggregate and hasAggregate macros

- README.md
- src/Http/Livewire/LivewireDatatable.php
Added defaultFilters. The defaultFilters should be an _Array_ of column names and the default filter value to use for. 
When a persisted filter ($this->persistFilters is true and session values are available) is available, it will override the default filters. 
<details>
<summary><b>Example Usage:</b></summary>
```php
<?php
use App\Models\User;
use Illuminate\Support\Carbon;
use Mediconesystems\LivewireDatatables\BooleanColumn;
use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;
use Mediconesystems\LivewireDatatables\NumberColumn;
class UsersTable extends LivewireDatatable
{
public $defaultFilters = [
'deleted_at' => '0',
];
public function builder()
{
return User::query()->withTrashed();
}
public function columns()
{ …
```
> Added defaultFilters to Livewire Datatables

- resources/views/livewire/datatables/datatable.blade.php
- resources/views/livewire/datatables/filters/checkbox.blade.php
- src/Http/Livewire/LivewireDatatable.php
If the search or filter is active, we must display the count of checked rows only for "visible" items (results of search or filtered results). Therefore, the toggleSelectAll() method must also check or uncheck all "visible" items when the search or filters are active.
See the gif below in order to view the correct behavior (what this PR brings)
> Bugfix checkboxes behavior when search or filters are active

- src/Http/Livewire/LivewireDatatable.php
Fix to prevent addGlobalSearch method to prepend tablePrefix when column contains '_concat_'. It was generating a syntax error in the query, i.e.:
SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION **DBNAME**.**TABLEPREFIX**CONCAT_WS does not exist
> fix addGlobalSearch method

- config/livewire-datatables.php
- resources/views/livewire/datatables/filters/datetime.blade.php
- src/DatetimeColumn.php
- src/Http/Livewire/LivewireDatatable.php
Currently this package only has the option to create a DateColumn or a Timecolumn. 
I've added the DatetimeColumn to the package, so now we are able to display date & time in a single column.
> Added a Datetime Column

- resources/views/livewire/datatables/filters/datetime.blade.php
- src/Http/Livewire/LivewireDatatable.php
Using version_compare to maintain downward compatibility.
Fixing bug: 
```
Too few arguments to function Illuminate\Database\Query\Expression::getValue(), 0 passed in /var/www/html/vendor/mediconesystems/livewire-datatables/src/Http/Livewire/LivewireDatatable.php on line 417 and exactly 1 expected
```
Based on the issue and fix of @daniftinca #584
> Fix missing grammar parameter in getValue() for laravel 10.
