- resources/views/livewire/datatables/datatable.blade.php
- resources/views/livewire/datatables/tailwind-simple-pagination.blade.php
First attempt at a pull request lol, apologies if it's not done correctly.
Just suggested a change to the pagination file and datatable.php styling for mobiles. 
PS I reversed the autoformat changes in the first commit (which is why there are 2) so that you can see the changes more easily.
> Mobile Pagination Changes

- composer.json
- src/Http/Livewire/LivewireDatatable.php
Needed some core changes to cope with php data beting serialised to js and back again
> Livewire 2

- composer.json
Updated composer.json
- Added laravel 8 support
- Added livewire 2 support
- Updated testbench so laravel 8 is supported
- Added legacy-factories so the current test suite keeps working
This PR closes #26.
> Added laravel 8 & livewire 2 support.

- resources/views/livewire/datatables/datatable.blade.php
- src/Http/Livewire/LivewireDatatable.php
- When there is no data in the table:
-  it shows a message `There's Nothing to show at the moment`
- no need to show the pagination and the dropdown
> Design enhancement 

- src/Http/Livewire/LivewireDatatable.php
`Array to string conversion  (View: /path/to/project/resources/views/livewire/datatables/datatable.blade.php)`
Trace Path `vendor/mediconesystems/livewire-datatables/src/Http/Livewire/LivewireDatatable.php:699`
Controller
```php
class CategoryTable extends LivewireDatatable
{
public $model = BackendCategory::class;
public function builder()
{
return BackendCategory::query();
}
public function columns()
{
return [
NumberColumn::name('id')
->label('ID')
->alignCenter(),
Column::name('name')
->label('Name')
->alignCenter()
->searchable()
->editable(),
Column::name('slug')
->alignCenter()
->searchable()
->label('Slug')
->editable(),
Column::name('order')
->alignCenter()
->label('Order')
->editable(),
Column::delete()
->label('Control')
->alignCenter(),
];
}
}
```
Views
```blade
...
<div …
```
> Eloquent Refactoring

- resources/views/livewire/datatables/tailwind-simple-pagination.blade.php
- src/Http/Livewire/LivewireDatatable.php
> Truncate search

- README.md
change alignCenter to alignRight
> docs: fix mistyped alignCenter

- resources/views/livewire/datatables/tailwind-pagination.blade.php
- resources/views/livewire/datatables/tailwind-simple-pagination.blade.php
- src/Http/Livewire/LivewireDatatable.php
This pull request fix malfunction on  fired event for previous button.
Fix for issue #57
> Fix event on previous button

- composer.json
- src/Column.php
- src/Http/Livewire/LivewireDatatable.php
useful if you want to add custom parameters
> add params to columns info

- src/Http/Livewire/LivewireDatatable.php
Fix for: https://github.com/MedicOneSystems/livewire-datatables/issues/200
> Fix reset to page 1 on search

- resources/views/livewire/datatables/datatable.blade.php
This makes search field look nicer out of the box.
> Make search field compatible with tailwindcss/forms

- src/Http/Livewire/LivewireDatatable.php
> Fix undefined array key error

- README.md
- src/BooleanColumn.php
- src/Column.php
- src/Http/Livewire/LivewireDatatable.php
- tests/ColumnTest.php
> Fixed exports

- README.md
- src/Column.php
Thanks @Thyseus,
#259
I have renamed you method so that it isn't a breaking change, and added details to the readme
> Thyseus improve link to

- src/Http/Livewire/LivewireDatatable.php
> Fixed bug #267

- src/NumberColumn.php
Formats & rounds a number with grouped thousands - 1000000 => 1,000,000.00 (If places set to 2) -  with variable places.
Decimal seperator -> .
Thousands seperator -> ,
> Add format method to Number Column.

- composer.json
- config/livewire-datatables.php
- src/Column.php
- src/Http/Livewire/LivewireDatatable.php
- tests/LivewireDatatableQueryBuilderTest.php
- tests/TestCase.php
The default hard set in code does not work with smalldatetime in MS SQL. This makes it configurable.
> Add support to set default date filter start and end to support other Date/DateTime types.

- src/Http/Livewire/LivewireDatatable.php
check which database driver is used and build the query according to its dialect. added SQLite dialect only, partially fiexs issue #183
> add SQLite dialect to resolveAdditionalSelects

- src/Http/Livewire/LivewireDatatable.php
It would be useful to be able to control the toggleGroup method from foreign livewire components
> Add an event listener for toggleGroup

- composer.json
I was successfully able to install and run the package with Laravel v10. There were no issues or errors during `composer update`.
> L10 compatibility

- src/Http/Livewire/LivewireDatatable.php
Fixes issue: https://github.com/MedicOneSystems/livewire-datatables/issues/572
> Fix error related to search with expressions on Laravel 10
